# This is a basic workflow to help you get started with Actions

name: Flux

# Controls when the workflow will run
on: [push]
  # Triggers the workflow on push or pull request events but only for the master branch
  # push:
  #   branches: [ master ]
  # pull_request:
  #   branches: [ master ]
permissions:
      id-token: write
      contents: read
jobs:
  flux:
    name: "Flex"
    runs-on: ubuntu-latest
    env:
      ARM_CLIENT_ID: ${{ secrets.AZURE_AD_CLIENT_ID }}
    #   ARM_CLIENT_SECRET: ${{ secrets.AZURE_AD_CLIENT_SECRET }}
    #   ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
    defaults:
      run:
        shell: bash

    steps:

    - uses: azure/k8s-set-context@v2
      with:
        method: service-account
        k8s-url: ${{ secrets.K8S_URL }}                                                                                                                           
        k8s-secret: ${{ secrets.K8S_SECRET }}

    - uses: azure/k8s-set-context@v2
      with:
        method: kubeconfig
        kubeconfig: ${{ secrets.KUBE_CONFIG }}
