# This is a basic workflow to help you get started with Actions

name: Flux

# Controls when the workflow will run
on: [push]
  # Triggers the workflow on push or pull request events but only for the master branch
  # push:
  #   branches: [ master ]
  # pull_request:
  #   branches: [ master ]
permissions:
      id-token: write
      contents: read
jobs:
  flux:
    name: "Flex"
    runs-on: ubuntu-latest
    # env:
      # ARM_CLIENT_ID: ${{ secrets.AZURE_AD_CLIENT_ID }}
    defaults:
      run:
        shell: bash

    steps:
    - name: 'Az CLI login'
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        enable-AzPSSession: true 

    - uses: azure/k8s-set-context@v2
      with:
        method: service-account
        k8s-url: ${{ secrets.K8S_URL }}                                                                                                                           
        k8s-secret: ${{ secrets.K8S_SECRET }}
      
    - name: 'Run az commands'
      run: |
        az account show
        az group list
        pwd
        ls

